---
title: "Attribution analysis & future climate change"
author: "Puvvula"
date: "9/16/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r pressure, echo=FALSE}

### LOAD REQUIRED LIBS ######################
library(tidyverse)
library(mgcv)
library(lubridate)
library(corrplot)
library(skimr)
library(weathermetrics)

coastal <- read_csv ("/work/jessebell/puvvula/coastal_octf.csv")
coastal<-read_csv ("/work/jessebell/puvvula/pied_octf.csv")

#filter by region for analysis

#data summary
skim(dat)

###### DATA FORMATTING ######################
coastal$date <- as.Date(coastal$date, format = "%m/%d/%Y")
coastal$month<- as.factor(month(coastal$date))
coastal$year<- as.factor(format(coastal$date, '%Y'))
coastal$dow <- wday(as.Date(coastal$date, format = "%m/%d/%Y"))
weekdays1 <- c('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday')
coastal$wDay <- factor((weekdays(coastal$date) %in% weekdays1), 
                       levels=c(FALSE, TRUE), labels=c('weekend', 'weekday'))
coastal$temp_c <- ((coastal$tmax - 32) * 0.5555556)


coastal$Steadman_HI <- heat.index(t = coastal$tmax,dp = coastal$dewpoint,
                                  temperature.metric = "fahrenheit")
# US NWS HI
coastal$NWS_HI<- heat.index.algorithm(t=coastal$tmax, rh=coastal$RH)
```

```{r, echo=FALSE}
#correlation plots - for continous variables in this study
################## Continous variables ######################
myvars <- c("Rate_ER_visit","Count_ER_visit","Avg_temp","Max_temp", "Min_temp", "DTR", "Dewpoint",
            "RH", "MAT","Steadman_HI", "NWS_HI", "Humidex", "TDI","EHF",
            )
dat<- piedmont[myvars]
M<-cor(dat, method = "spearman", use = "complete.obs")

##################### CORR MATRIX- MATRIX FUNCTION #############
cor.mtest <- function(mat, ...) {
  mat <- as.matrix(mat)
  n <- ncol(mat)
  p.mat<- matrix(NA, n, n)
  diag(p.mat) <- 0
  for (i in 1:(n - 1)) {
    for (j in (i + 1):n) {
      tmp <- cor.test(mat[, i], mat[, j], ...)
      p.mat[i, j] <- p.mat[j, i] <- tmp$p.value
    }
  }
  colnames(p.mat) <- rownames(p.mat) <- colnames(mat)
  p.mat
}
# matrix of the p-value of the correlation
p.mat <- cor.mtest(dat)
head(p.mat[, 1:15])

#Correlation matrix
col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))
corrplot(M, method="color", col=col(200),  
         type="upper", order="hclust", 
         addCoef.col = "black", # Add coefficient of correlation
         tl.col="black", tl.srt=45, #Text label color and rotation
         # Combine with significance
         p.mat = p.mat, sig.level = 0.01, insig = "blank", 
         # hide correlation coefficient on the principal diagonal
         diag=FALSE)

```

```{r, echo=FALSE}
# GAM - Model building and comparision

m1<- gam(imp_rate ~ s(max_appt,k=5, bs='cr')+wDay+month+year,
         family=Gamma(link = log),
         method = "GCV.Cp",
         data=coastal)

summary(m1)
m1$aic
gam.check(m1)

m2<- gam(imp_rate ~ s(app_temp,k=5, bs='cr'),
         family=Gamma(link = log),
         method = "GCV.Cp",
         data=coastal)

summary(m2)
m2$aic

anova(m1, m2, test = "Chisq")
plot.gam(m1)
```

```{r}
#Prediction - Climate attribution analysis (current)
##########################
testset<- read_csv("C:\\Users\\jagad\\Desktop\\NC_Sur\\
                   Nautal_scenario\\coas_Nat_act.csv")
testset$date <- as.Date(testset$Date, format = "%m/%d/%Y")
testset$month<- as.factor(month(testset$date))
testset$year<- as.factor(format(testset$date, '%Y'))
testset$dow <- as.factor (wday(as.Date(testset$date, 
                                       format = "%m/%d/%Y")))
testset$Max_temp<- as.numeric(testset$tmax_nat)
testset$NWS_HI<- heat.index.algorithm(t=testset$Max_temp, rh=testset$RH)
testset$tmax_preder_vis<-predict(m1, testset)
testset$NWSHI_preder_vis<-predict(m2, testset)

testset$tmax_pred_exp<- as.numeric(exp(testset$tmax_preder_vis))
testset$tmax_pred_count<- as.numeric(((testset$tmax_pred_exp)*2741101)/100000)
write_csv(testset, "C:/Users/jagad/Desktop/NC_Sur/
          Nautal_scenario/Nat_final/coastal_predictions_nat_sce.csv", row.names = F)


```



```{r}
#Prediction - future climate change

x<- read_csv("C:/Users/jagad/Desktop/NC_manus/future_clim_dat/
             coas_densityplt.csv")
x$Max_temp<- ((x$Tmax *(9/5))+32)
x$Max_temp<- as.numeric(x$Max_temp)

x$pred_ER<-exp(predict(m1, x))

write_csv(x, "C:/Users/jagad/Desktop/NC_manus/future_clim_dat
          /coas_densityplt_pred.csv")
```



```{r, echo=FALSE}
#########################
#Association b/w maximum temperature and HRI ER visits
#Supplement.2-A
library(visreg)

p.coas <- visreg(m1,  scale='response', "temp_c", line.par = list(col = 'red'), plot=FALSE)
p.pied <- visreg(m2,  scale='response', "temp_c", plot = FALSE)

dplyr::bind_rows(
  dplyr::mutate(p.coas$fit, plt = "Coastal"),
  dplyr::mutate(p.pied$fit, plt = "Piedmont")
) -> fits

ggplot() +
  geom_ribbon(
    data = fits, 
    aes(temp_c, ymin=visregLwr, ymax=visregUpr, group=plt), 
    fill="gray90") +
  geom_line(data = fits, aes(temp_c, visregFit, group=plt, color=plt)) +
  labs(x="Maximum temperature (°C)", 
       y="Rate of HRI morbidity (per 100,000)")+
  xlim(15,40)+
  theme_bw()+ theme(panel.border = element_blank(), 
                    panel.grid.major = element_blank(),
                    panel.grid.minor = element_blank(), 
                    axis.line = element_line(colour = "black"))+
  theme(
    legend.position='bottom',
    axis.line = element_line(colour = "black"),
    text=element_text(size=12, family = "Helvetica"),
    axis.text=element_text(size=10, family = "Helvetica"),
    axis.title=element_text(size=12, family = "Helvetica"),
    plot.title=element_text(size=12, family = "Helvetica"),
    legend.text=element_text(size=12, family = "Helvetica"),
    legend.title=element_blank())+
  theme(strip.text.x = element_blank(),
       strip.background = element_rect(colour="transparent", 
                                      fill="transparent"),
     legend.position=c(0.2,0.90))


ggsave("/work/jessebell/puvvula/supp_2a.tiff", 
       width = 4,height = 4)

```


```{r}
#future climate change group differences
dat_three<- read_csv("/work/jessebell/puvvula/fig_three.csv")
dat_three$RCP<-as.factor(dat_three$RCP)
dat_three$temp_c <- ((dat_three$Max_temp - 32) * 0.5555556)

#comparing hot days
dat_three$hot_day<- as.factor(cut(dat_three$temp_c,c(0,29.99,40), labels=c(0,1)))

#filter by below for timeseries wise comparison
#filter just by region for rcp scale comparison
coastal_dat<-filter(dat_three,region=="Coastal" & RCP=="8.5")
pied_dat<-filter(dat_three,region=="Piedmont" & RCP=="8.5")

tbl<-table(coastal_dat$RCP, coastal_dat$hot_day)
chisq.test(tbl)

tbl<-table(pied_dat$Time_period, pied_dat$hot_day)
chisq.test(tbl)

#comparing HRI - future climate change
#mean difference between two groups
pied_dattt<-filter(dat_three,region=="Piedmont" & period=="lc" & Model=="GFDL")

#check for mid scenario and late scenario
#high to low emission scenario HRI comparison
pied_dattt %>% 
  group_by(RCP) %>% 
  summarize(q1 = median(pred_ER))

t.test(pied_dattt$pred_ER ~ pied_dattt$RCP, paired=T)

#HRI comparison across time frame ?ANOVA
pd_dat<-filter(dat_three,region=="Piedmont" & RCP=="8.5" & Model=="CCSM4")

group_by(pd_dat, period) %>%
  summarise(
    count = n(),
    medi = median(pred_ER, na.rm = TRUE))
res.aov <- aov(pred_ER ~ period, data = pd_dat)
summary(res.aov)
```


```{r, echo=FALSE}
# Manuscript figures
#Figure. 1
library(tidyverse)
dat<- read_csv("/work/jessebell/puvvula/attr_fig_one.csv")
dat$Temp_c <- ((dat$Temp - 32) * 0.5555556)

#comparing hot days
dat$hot_day<- as.factor(cut(dat$Temp_c,c(0,29.9999,40), labels=c(0,1)))

coastal_dat<-filter(dat,Region=="Coastal")
pied_dat<-filter(dat,Region=="Piedmont")

tbl<-table(pied_dat$Category, pied_dat$hot_day)
chisq.test(tbl)

########
library(extrafont)
loadfonts()

ggplot(dat, aes(x=Temp_c, colour=Category, linetype=Category))+
  geom_density()+
  scale_linetype_manual(values=c(5,1))+
  scale_color_manual(values=c('blue','firebrick1'))+
  xlab("Maximum temperature (°C)")+
  ylab("Density")+
  facet_grid((Region~.), scales="fixed")+
  theme(axis.line = element_line(colour = "black"))+
  theme_bw()+
  theme(legend.position='bottom')+
  theme(text=element_text(size=12, family = "Helvetica"), 
        axis.text=element_text(size=10, family = "Helvetica"), 
        axis.title=element_text(size=12, family = "Helvetica"), 
        plot.title=element_text(size=12, family = "Helvetica"), 
        legend.text=element_text(size=12, family = "Helvetica"), 
        legend.title=element_blank()+
  strip.text.y = element_blank())

ggsave("fig_one.tiff", 
       width = 4,height = 9)

#Remove facet label        
#strip.text.y = element_blank())

#placing legend inside the plot
  #theme(strip.text.x = element_blank(),
   #     strip.background = element_rect(colour="transparent", 
    #                                    fill="transparent"),
     #   legend.position=c(0.1,0.95))
```


```{r, echo=FALSE}

##################
##################
#Figure. 2
library(lubridate)
dat_two<- read_csv("/work/jessebell/puvvula/fig_two.csv")

#comparing HRI
coastal_dat<-filter(dat_two,Region=="Coastal")
pied_dat<-filter(dat_two,Region=="Piedmont")

#wide to long conversion
dat_test<-gather(coastal_dat, scene, measure, 
                 Natural:Observed, factor_key = T)

t.test(dat_test$measure ~ dat_test$scene, paired=T)


dat_two$Date <- as.Date(dat_two$Date, format = "%m/%d/%Y")
dat_two$Month<- as.factor(months(dat_two$Date))
dat_two$Year<- as.factor(format(dat_two$Date, '%Y'))

#Reorder month variable
dat_two$Month <- factor(dat_two$Month, 
                        levels=c("May", "June", 
                                 "July", "August", "September"))

#percent increase in ER visit estimation
dat_two$anomaly<- ((dat_two$Observed-dat_two$Natural)/
                     dat_two$Natural)*100
#positive value - percent increase
#negative value - percent decrease

dat_two %>% 
  group_by(Region, Month, Year) %>% 
  summarize(anomaly_median = quantile(anomaly, 0.50),
            anomaly_LL = quantile(anomaly, 0.25),
            anomaly_UL = quantile(anomaly, 0.75))


ggplot(dat_two, aes(Year, anomaly)) +
  geom_boxplot( alpha=0.2, aes(fill=Month), 
                outlier.size=1)+
  facet_grid(Region~., scales="fixed")+
  ylim(-100,1000)+
  labs(x="Year",
       y="HRI morbidity attributable to climate change (%)")+
  geom_hline(yintercept = 0, linetype="dashed", color="grey")+
  theme_bw() + theme(panel.border = element_blank(), 
                     panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(), 
                     axis.line = element_line(colour = "black"))+
  theme(
    legend.position='bottom',
    axis.line = element_line(colour = "black"),
    text=element_text(size=12, family = "Helvetica"),
    axis.text=element_text(size=10, family = "Helvetica"),
    axis.title=element_text(size=12, family = "Helvetica"),
    plot.title=element_text(size=12, family = "Helvetica"),
    legend.text=element_text(size=12, family = "Helvetica"),
    legend.title=element_blank())

ggsave("/work/jessebell/puvvula/fig_two.tiff", 
       width = 6,height = 6)
```


```{r, echo=FALSE}


###########################
###########################
#Figure.3
dat_three<- read_csv("/work/jessebell/puvvula/fig_three.csv")
dat_three$temp_c <- ((dat_three$Max_temp - 32) * 0.5555556)

################
ggplot(dat_three, aes(Time_period, pred_ER, group=Time_period)) +
  geom_boxplot(varwidth = TRUE, alpha=0.2, aes(fill=Time_period))+
  facet_grid(region~RCP+Model, scales="fixed")+
  labs(x="", y="Rate of HRI morbidity (per 100,000)")+
  theme_bw() + 
  theme(panel.border = element_blank(), 
                     panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(), 
                     axis.line = element_line(colour = "black"))+
  theme(
    legend.position='bottom',
    axis.line = element_line(colour = "black"),
    text=element_text(size=12, family = "Helvetica"),
    axis.text=element_text(size=10, family = "Helvetica"),
    axis.title=element_text(size=12, family = "Helvetica"),
    plot.title=element_text(size=12, family = "Helvetica"),
    legend.text=element_text(size=12, family = "Helvetica"),
    legend.title=element_blank())+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

ggsave("/work/jessebell/puvvula/fig_three.tiff", 
       width = 8,height = 6)

####################################################
####################################################
```


```{r}
#########################################
#Supplement. 6
##### GFDL CCSM correlation ####
x<- read.csv("C:\\Users\\jagad\\Desktop\\NC_manus\\future_clim_dat\\
             pied.csv", header = T,
             fileEncoding="UTF-8-BOM")
cor(x$ccsm4_45_tasmax_1116, x$gfdl_45_tasmax_1116, method = "pearson")

```

```{r}
################################
#supplement. 7
x<-read_csv("/work/jessebell/puvvula/fig_three.csv")

x$temp_c<- ((x$Max_temp -32)*0.5555556)
x$RCP<-as.factor(x$RCP)

ggplot(x, aes(x=temp_c, colour=RCP, linetype = region))+ 
  geom_density()+facet_grid(Model~Time_period)+
  labs(x="Temperature (°C)", y="Density")+
  #xlim()+
  theme_bw() + 
  theme(panel.border = element_blank(), 
                     panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(), 
                     axis.line = element_line(colour = "black"))+
  theme(
    legend.position='bottom',
    axis.line = element_line(colour = "black"),
    text=element_text(size=12, family = "Helvetica"),
    axis.text=element_text(size=10, family = "Helvetica"),
    axis.title=element_text(size=12, family = "Helvetica"),
    plot.title=element_text(size=12, family = "Helvetica"),
    legend.text=element_text(size=12, family = "Helvetica"),
    legend.title=element_blank())
  
ggsave("/work/jessebell/puvvula/sup_seven.tiff", 
       width = 10,height = 10)


  
```


```{r}

library(tidyverse)
library(dlnm)
library(splines)
library(lubridate)
library(mgcv)
#=================================================================================
#coastal
dat <- read_csv("/work/jessebell/puvvula/coastal_octf.csv")

#piedmont
dat <- read.csv ("/work/jessebell/puvvula/pied_octf.csv")

dat$date <- dat$Date # only for piedmont
# ==================================================================================
dat$date <- as.Date(dat$date, format = "%m/%d/%Y")
dat$dow <- wday(as.Date(dat$date, format = "%m/%d/%Y"))
dat$month<- as.factor(month(dat$date))
dat$year<- as.factor(format(dat$date, '%Y'))
weekdays1 <- c('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday')
dat$wDay <- factor((weekdays(dat$date) %in% weekdays1), 
                       levels=c(FALSE, TRUE), labels=c('weekend', 'weekday'))

cat <- c("month", "dow", "wDay", "year")
dat[cat] <- lapply(dat[cat], factor)
dat$Rate_ER_visit <- as.numeric(dat$imp_rate)
dat$Count_ER_visit <- as.numeric(dat$imp_count)
dat$Max_temp <- as.numeric(dat$tmax)
dat$temp_c<- ((dat$tmax- 32) * 0.5555556)
# ==================================================================================
varknots <- equalknots(dat$temp_c,fun="bs",df=5,degree=2)
lagknots <- logknots(5, 1)
cb3.temp <- crossbasis(dat$temp_c, lag=5, 
                       argvar=list(fun="bs",knots=varknots), arglag=list(knots=lagknots))
model3 <- gam(Count_ER_visit ~ cb3.temp+dow+month+year,
              family=quasipoisson(), dat)
# ==================================================================================
#how to set the cen value
pred3.temp <- crosspred(cb3.temp, model3,coef=NULL, vcov = NULL,
                        cen=32.23, by=1, 
                        from = 17, to = 37)

#Print risk ratio matrix
print(pred3.temp$allRRfit)

#3d plot - mostly useless
plot(pred3.temp, xlab="Temperature (°C)", zlab="RR", theta=200, phi=40,
     lphi=30,main="3D graph of temperature effect")


#relative risk | Temperature | lag
plot(pred3.temp, "contour", xlab="Temperature", key.title=title("RR"),
     plot.title=title("Contour plot",
                      xlab="Temperature (°C)",ylab="Lag"))

#what happens at different lags and temp values [change var=c() for temp | lag=c() for lag days] 
plot(pred3.temp, "slices", var=c(32,35), lag=c(0,5), col=4,
     ci.arg=list(density=40,col=grey(0.7)))

# ==================================================================================


```


