---
title: "Heat wave definition evaluation"
author: "Puvvula"
date: "9/16/2021"
output: pdf_document
---

```{r}
library(tidyverse)
library(lubridate)
library(weathermetrics)
library(ThermIndex)
library(janitor)
library(skimr)
#library(rcompanion)
```


```{r, echo=FALSE}
dat<- read_csv("/work/jessebell/puvvula/h_def_2021nov.csv")

dat$date <- as.Date(dat$date, format = "%m/%d/%Y")
dat$month<- as.factor(month(dat$date))
dat$year<- as.factor(format(dat$date, '%Y'))
dat$dow <- wday(as.Date(dat$date, format = "%m/%d/%Y"))
weekdays1 <- c('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday')
dat$wDay <- factor((weekdays(dat$date) %in% weekdays1), 
                       levels=c(FALSE, TRUE), labels=c('weekend', 'weekday'))

fct<- c(2, 13:68)
dat[,fct]<-lapply(dat[,fct],factor)
skim(dat)

dat$tmax_cel<- as.numeric(tempftoc(dat$tmax)) #convert F to C
dat$HI_17<- as.factor(ifelse(dat$tmax_cel >= 35, 1,0))
```

```{r}
#filter by region

coas<- dat %>% subset(Region=="Coastal")
pied<- dat %>% subset(Region=="Piedmont")

#additional definitions for Coastal
coas$shw_17 <- as.factor(ifelse(coas$tmax_cel >= 35, 1,0))
coas$shw_26 <- as.factor(ifelse(coas$app_temp >= 95.85, 1,0)) #85th pct
coas$shw_27 <- as.factor(ifelse(coas$app_temp >= 97.16, 1,0)) #90th pct
coas$shw_28 <- as.factor(ifelse(coas$app_temp >= 98.99, 1,0)) #95th pct


#additional definitions for Piedmont
quantile(pied$app_temp, probs = c(0.95, 0.90, 0.85))

pied$shw_17 <- as.factor(ifelse(pied$tmax_cel >= 35, 1,0))
pied$shw_26 <- as.factor(ifelse(pied$app_temp >= 95.47, 1,0)) #85th pct
pied$shw_27 <- as.factor(ifelse(pied$app_temp >= 96.66, 1,0)) #90th pct
pied$shw_28 <- as.factor(ifelse(pied$app_temp >= 98.52, 1,0)) #95th pct
```

```{r}
#testing group differences - identifying co-variates
library(stats)

#weekday - t-test: Result showed significant difference[mean weekend=0.36; weekday=0.45]
t.test(coas$imp_rate ~ factor(coas$wDay),
       paired=F,
       var.equal=F,
       conf.level=0.95)

#year - one way ANOVA: Values are significantly different by year
summary(aov(coas$imp_rate ~ factor(coas$year)))
TukeyHSD(aov(coas$imp_rate ~ factor(coas$year)))

#month - ANOVA
summary(aov(coas$imp_rate ~ factor(coas$month)))
TukeyHSD(aov(coas$imp_rate ~ factor(coas$month)))

#nws_hw - t-test: found significant difference between groups
t.test(coas$imp_rate ~ factor(coas$NWS_HW),
       paired=F,
       var.equal=F,
       conf.level=0.95)

```


```{r}
#statistical model:
#Using wDay+month+year+NWS_HW as covariates as there are significant 
#group mean differences

library(MASS)

coas$pop<- as.numeric(2741101)
pied$pop<- as.numeric(5571983)
#Coastal: 2741101
#Piedmont: 5571983

hw1<- glm.nb(imp_cnt~as.factor(shw_01)
             +rh+wDay+month+year+NWS_HW+
               offset(log(pop)),
             data=coas)
(est <- cbind(Estimate = coef(hw1), confint(hw1)))
exp(est)

#comparison of best performing models
anova(hw1,hw2,test="Chisq")
```

hw1<- glm.nb(imp_cnt~as.factor(shw_28)
             +rh+wDay+month+year+NWS_HW+
               offset(log(pop)),
             data=pied)
(est <- cbind(Estimate = coef(hw1), confint(hw1)))
exp(est)
summary(hw1)

```{r}
################################################################3
################################################################3
#Figure.1
library(tidyverse)

#Data for un-adjusted results
#res<-read_csv("/work/jessebell/puvvula/heatwave_tbl.csv")
#res<- read_csv("/work/jessebell/puvvula/h_def_adjusted.csv")

res<- read_csv("/work/jessebell/puvvula/h_def_adjusted_rh.csv")
cbbPalette <- c("#D55E00", "#0072B2", "#009E73", "#E69F00")

res$Region<-factor(res$Region, levels = c("Coastal", "Piedmont"))

res$meas<-as.factor(res$meas)
#levels(res$metric)
res$Metric<- factor(res$meas, levels = c("Mean", 
                                           "Maximum",
                                           "Minimum",
                                           "Maximum AT"))
                                           
res$Threshold_type<- factor(res$Threshold, levels = c("Seasonal", "Monthly", "Absolute"))

res$order<-factor(res$order, levels = c(1:110))


ggplot(res, aes(x = as.factor(order), y = irr, ymin = lcl, ymax = ucl,
                shape=Region, linetype=Threshold_type)) + 
  geom_pointrange(aes(col = Metric), 
                  position=position_dodge(width=1.5),size = 0.5) +
  ylab("Incidence rate ratio [95% CI]") +
  scale_y_continuous(breaks = seq(-1, 5, 1),limits=c(-1, 5))+
  geom_hline(aes(yintercept = 1)) + 
  scale_colour_manual(values=cbbPalette) + 
  ggtitle("")+
  xlab("Heat wave definitions")+
  theme_bw()+
  theme(axis.line = element_line(colour = "black"))+
  theme(panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        plot.title = element_text(hjust = 0.5),
        text=element_text(size=12,  family="Arial Black"),
        axis.text = element_text(size = 8, family="Arial Black"),
        axis.text.x = element_text(angle = 90, hjust = 0.5),
        legend.text.align = 0,
        strip.text=element_text(size=5.5),
        strip.placement = "outside",
        legend.box.just = "right",
        legend.spacing = unit(0, "cm"),
        legend.position = c(0.87,0.95),
        legend.box = "horizontal")+
  facet_grid(.~Heat_wave_definition, scales = "free", switch = "x", space = "free_x")

ggsave("/work/jessebell/puvvula/h_def_adj.tiff", 
       width = 18,height = 8)
```


```{r}
#
dat<- read_csv("/work/jessebell/puvvula/h_def_2021nov.csv")
dat_n<- dat %>% select("date", "Region", "shw_07", "shw_15", "NWS_HW")

#long to wide
dat_w<- dat_n %>% pivot_wider(names_from = Region, values_from = c(shw_07,shw_15, NWS_HW))

#McNemar test (Matched/paired t-test)
#Comparing SHW_15 - coastal with shw_08 - piedmont
table(dat_w$shw_15_Coastal, dat_w$shw_07_Piedmont) #2 by 2 table
prop.table(table(dat_w$shw_15_Coastal, dat_w$shw_07_Piedmont),margin = 2)*100 #proportion table
mcnemar.test(dat_w$shw_15_Coastal, dat_w$shw_07_Piedmont)

#COASTAL : Comparing shw_15 with NWS_HW
table(dat_w$shw_15_Coastal, dat_w$NWS_HW_Coastal) #2 by 2 table
prop.table(table(dat_w$shw_15_Coastal, dat_w$NWS_HW_Coastal),margin = 2)*100 #proportion table
mcnemar.test(dat_w$shw_15_Coastal, dat_w$NWS_HW_Coastal)

#PIEDMONT : Comparing shw_07 with NWS_HW
table(dat_w$shw_07_Piedmont, dat_w$NWS_HW_Piedmont) #2 by 2 table
prop.table(table(dat_w$shw_07_Piedmont, dat_w$NWS_HW_Piedmont),margin = 2)*100 #proportion table
mcnemar.test(dat_w$shw_07_Piedmont, dat_w$NWS_HW_Piedmont)
```


```{r}
#figure 2
dat<- read_csv("/work/jessebell/puvvula/h_def_2021nov.csv") %>% select("date", "Region", "tmax", "tavg","shw_07", "shw_15", "NWS_HW","imp_rate")


#subset region
df<- dat %>% filter(Region=="Coastal")
df$hw<- factor(as.numeric(as.factor(!df$shw_15):as.factor(!df$NWS_HW)))

#heat wave levels: 
#1 = hw=1 & NWS=1 || 2 = hw=1 & NWS=0 || 3 = hw=0 & NWS=1 || 4 = hw=0 & NWS=0

df$tmax_c<- ((df$tmax - 32) * 0.5555556)

df$Heat_wave <- recode(df$hw,
                       `1`="SWH_15_HW/NWS_HW",
                       `2`="SWH_15_HW/NWS_NHW",
                       `3`="SWH_15_NHW/NWS_HW",
                       `4`="SWH_15_NHW/NWS_NHW")

cbbPalette <- c("#D55E00", "#0072B2", "#009E73", "#E69F00")
ggplot(df, aes(x=tmax_c, y=imp_rate, color=Heat_wave))+
  geom_point(size=1)+
  scale_colour_manual(values=cbbPalette)+
  labs(x="Daily maximum temperature (°C)", 
       y="Rate of HRI Morbidity (per 100,000)")+
  scale_x_continuous(breaks = seq(25, 38, 2),limits=c(25,38))+
  scale_y_continuous(breaks = seq(0, 4, 0.5),limits=c(0,4))+
  theme_bw()+
  theme(axis.line = element_line(colour = "black"))+
  theme(panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        plot.title = element_text(hjust = 0.5),
        text=element_text(size=12,  family="Arial Black"),
        axis.text = element_text(size = 8, family="Arial Black"),
        axis.text.x = element_text(angle = 0, hjust = 0.5),
        legend.text.align = 0,
        strip.text=element_text(size=5.5),
        strip.placement = "outside",
        legend.box.just = "right",
        legend.spacing = unit(0, "cm"),
        legend.position = c(0.18,0.87),
        legend.box = "horizontal")
ggsave("/work/jessebell/puvvula/h_def_comp_coas.tiff", 
       width = 8,height = 6)

###############
###############

#subset region
df<- dat %>% filter(Region=="Piedmont")
df$hw<- factor(as.numeric(as.factor(!df$shw_07):as.factor(!df$NWS_HW)))

#heat wave levels: 
#1 = hw=1 & NWS=1 || 2 = hw=1 & NWS=0 || 3 = hw=0 & NWS=1 || 4 = hw=0 & NWS=0

df$tmin_c<- ((df$tavg - 32) * 0.5555556)

df$Heat_wave <- recode(df$hw,
                       `1`="SWH_07_HW/NWS_HW",
                       `2`="SWH_07_HW/NWS_NHW",
                       `3`="SWH_07_NHW/NWS_HW",
                       `4`="SWH_07_NHW/NWS_NHW")

cbbPalette <- c("#D55E00", "#0072B2", "#009E73", "#E69F00")
ggplot(df, aes(x=tmin_c, y=imp_rate, color=Heat_wave))+
  geom_point(size=1)+
  scale_colour_manual(values=cbbPalette)+
  labs(x="Daily minimum temperature (°C)", 
       y="Rate of HRI Morbidity (per 100,000)")+
  scale_x_continuous(breaks = seq(20, 32, 2),limits=c(20, 32))+
  theme_bw()+
  theme(axis.line = element_line(colour = "black"))+
  theme(panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        plot.title = element_text(hjust = 0.5),
        text=element_text(size=12,  family="Arial Black"),
        axis.text = element_text(size = 8, family="Arial Black"),
        axis.text.x = element_text(angle = 0, hjust = 0.5),
        legend.text.align = 0,
        strip.text=element_text(size=5.5),
        strip.placement = "outside",
        legend.box.just = "right",
        legend.spacing = unit(0, "cm"),
        legend.position = c(0.2,0.87),
        legend.box = "horizontal")


ggsave("/work/jessebell/puvvula/h_def_comp_pied.tiff", 
       width = 8,height = 6)
```

