---
title: "Heat wave definition evaluation"
author: "Puvvula"
date: "9/16/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}

library(tidyverse)
library(lubridate)
library(weathermetrics)
library(ThermIndex)
library(rcompanion)

dat<- read_csv("/work/jessebell/puvvula/NC_heatdef.csv")

piedmont$EHF<- ehf(piedmont$tmax, piedmont$tmin, t95 = 80.55)

#Steadman HI
piedmont$Steadman_HI <- heat.index(t = piedmont$tmax,dp = piedmont$Dewpoint,
                                  temperature.metric = "fahrenheit")
# US NWS HI
piedmont$NWS_HI<- heat.index.algorithm(t=piedmont$tmax, rh=piedmont$RH)

piedmont$tavg_cel<- as.numeric(tempftoc(piedmont$Avg_temp)) #convert F to C
piedmont$Humidex <- as.numeric(humidex(piedmont$tavg_cel, piedmont$RH))

#thermal discomfort index
piedmont$TDI <- as.numeric(di(piedmont$tavg_cel, piedmont$RH))


# Tan et al HW definition
piedmont$tmax_cel<- as.numeric(tempftoc(piedmont$tmax)) #convert F to C
piedmont$HI_17<- as.factor(ifelse(piedmont$tmax_cel >= 35, 1,0))


#Steadman definitions
piedmont$HI_26 <- as.factor(ifelse(piedmont$MAT >= 95.85, 1,0)) #85th pct
piedmont$HI_27 <- as.factor(ifelse(piedmont$MAT >= 97.16, 1,0)) #90th pct
piedmont$HI_28 <- as.factor(ifelse(piedmont$MAT >= 98.99, 1,0)) #95th pct

cat1 <- c("tavg_95_2_pie","tavg_98_2_pie","tavg_95_3_pie","tavg_98_3_pie","tavg_90_2_pie",
         "tavg_90_3_pie","tmax_95_3_pie","tmax_98_2_pie","tmax_98_3_pied","tmax_90_2_pie",
         "tmax_90_3_pie","tmax_95_2_pie","tmin_90_2_pie","tmin_90_3_pie","tmin_95_2_pie",
         "tmin_95_3_pie","tmin_98_2_pie","tmin_98_3_pie" ,"Tmin_99_2", "Tmin_99_3",
         "Tmax_99_2","Tmax_99_3", "Tavg_99_2","Tavg_99_3", "dow", "wDay")
piedmont[cat1] <- lapply(piedmont[cat1], factor)

piedmont$EHF<- as.numeric(piedmont$EHF)
piedmont$Rate_ER_visit <- as.numeric(piedmont$imp_rate)
piedmont$Log_rate_ER_visit<- log(piedmont$Rate_ER_visit)
piedmont$Count_ER_visit <- as.numeric(piedmont$imp_count)
piedmont$Max_temp <- as.numeric(piedmont$tmax)
piedmont$Min_temp <- as.numeric(piedmont$tmin)
piedmont$Avg_temp <- as.numeric(piedmont$TAVG)
piedmont$DTR <- as.numeric(piedmont$tmax-piedmont$tmin)
piedmont$MAT<- as.numeric(piedmont$max_appt)
piedmont$Dewpoint<- as.numeric(piedmont$dpt)
piedmont$RH<-as.numeric(piedmont$RH)

```


```{r}
#statistical model

hw1<- glm.nb(imp_count~tavg_90_3_coas,data=coastal)
(est <- cbind(Estimate = coef(hw1), confint(hw1)))
exp(est)
```



```{r}
################################################################3
################################################################3
#Figure.2
library(tidyverse)
res<-read_csv("/work/jessebell/puvvula/heatwave_tbl.csv")
cbbPalette <- c("#D55E00", "#0072B2", "#009E73", "#E69F00")

res$Region<-factor(res$Region, levels = c("Coastal", "Piedmont"))

res$meas<-as.factor(res$meas)
#levels(res$metric)
res$Metric<- factor(res$meas, levels = c("Mean", 
                                           "Maximum",
                                           "Minimum",
                                           "Maximum AT"))
                                           
res$Threshold_type<- factor(res$Threshold, levels = c("Seasonal", "Monthly"))

res$order<-factor(res$order, levels = c(1:112))


ggplot(res, aes(x = as.factor(order), y = or, ymin = lcl, ymax = ucl,
                shape=Region, linetype=Threshold_type)) + 
  geom_pointrange(aes(col = Metric), 
                  position=position_dodge(width=1.5),size = 0.5) +
  ylab("Incidence rate ratio [95% CI]") +
  scale_y_continuous(breaks = seq(-1, 19, 1),limits=c(-1, 19))+
  geom_hline(aes(yintercept = 1)) + 
  scale_colour_manual(values=cbbPalette) + 
  ggtitle("")+
  xlab("Heat wave definitions")+
  theme_bw()+
  theme(axis.line = element_line(colour = "black"))+
  theme(panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        plot.title = element_text(hjust = 0.5),
        text=element_text(size=12,  family="Arial Black"),
        axis.text = element_text(size = 8, family="Arial Black"),
        axis.text.x = element_text(angle = 90, hjust = 1),
        legend.text.align = 0,
        strip.text=element_text(size=5.5),
        strip.placement = "outside",
        legend.box.just = "right",
        legend.spacing = unit(0, "cm"),
        legend.position = c(0.83,0.90),
        legend.box = "horizontal")+
  facet_grid(.~Heat_wave_definition, scales = "free", switch = "x", space = "free_x")

```



```{r}
#Miscellaneous 

x<- read_csv("C:/Users/jagad/Desktop/NC_manus/HW_coas_pied_comp.csv")
x$HW_cos<- ifelse(x$coas_tmax>= 95, 1, 0)
x$HW_pied<- ifelse(x$pied_tmax>=95, 1, 0)
cor(x$HW_cos, x$HW_pied, method = "pearson")

#Matched/paired t-test
table(x$HW_cos, x$HW_pied) #2 by 2 table
prop.table(table(x$HW_cos, x$HW_pied),margin = 2)*100 #proportion table
mcnemar.test(x$HW_cos, x$HW_pied) # McNemar test (for binary data)
#t.test(x$HW_cos, x$HW_pied, paired = TRUE, alternative = "two.sided") #paired t test

#correlation between heatwave definition 17 and NWS database
x<- read_csv("C:/Users/jagad/Desktop/pied_cor.csv")
cor(x$hw_17, x$nws_hi, method = "pearson", use = "complete.obs")
prop.table(table(x$hw_17, x$nws_hi),margin = 1)*100 #margin =2 for column percentages
mcnemar.test(x$hw_17, x$nws_hi)
```

